version: '3.8'

services:
  reagent-db:
    image: postgres:17
    container_name: reagent-db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: reagent_db
    ports:
      - '5433:5432'
    volumes:
      - reagent-db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  reagent-app:
    build: .
    container_name: reagent-app-container
    environment:
      NODE_ENV: production
      API_URL: "https://example.com/api"
      PORT: 3002
      DB_HOST: reagent-db
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: reagent_db
      DATABASE_URL: "postgresql://postgres:3430@reagent-db:5432/reagent_db"
    ports:
      - '3002:3002'
    depends_on:
      - reagent-db
    restart: always

volumes:
  reagent-db-data:
